version: "3"

services:
  blog-backend-nestjs-db:
    image: postgres:14-alpine
    volumes:
      - "/etc/postgresql"
      - "/var/log/postgresql"
      - "/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: dg
      POSTGRES_USER: dg
      POSTGRES_DB: dg
    ports:
      - "5432:5432"

volumes:
  cache:
    driver: local
