version: "3"

services:
  blog-backend-nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start:dev
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  blog-backend-nestjs-db:
    image: postgres:14-alpine
    volumes:
      - "/etc/postgresql"
      - "/var/log/postgresql"
      - "/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: dg
      POSTGRES_USER: dg
      POSTGRES_DB: dg
    ports:
      - "5432:5432"

volumes:
  node_modules:
  cache:
    driver: local
